version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8099:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /Users/xiewei/workspace/OMP-frontend/dist:/usr/share/nginx/html
