#!/bin/bash
set -e

docker stop zoonavigator || true
docker rm -f zoonavigator || true

docker build --file zoonavigator/Dockerfile --force-rm --tag zoonavigator .
exec docker run -d -p 9000:9000 --name zoonavigator --restart unless-stopped zoonavigator